apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceaccount.yaml
- Backend/
- Frontend/
- Redis/
images:
- name: 636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-backend
  newName: 636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-backend
  newTag: backend-4
- name: 636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-frontend
  newName: 636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-frontend
  newTag: frontend-4
