apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-app
  namespace: taskmanager
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
