apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db_credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: friends
    creationPolicy: Owner
  datafrom:
    - extract :
        key: prod/DB_CREDENTIALS
    