serviceAccount:
  create: true
  name: argocd-image-updater
  annotations: {}

config:
  argocd:
    grpcWeb: true
    serverAddress: "http://argocd-server.argocd.svc.cluster.local"
    insecure: true
    plaintext: true
  
  registries:
    - name: ecr
      # api_url: https://608713827966.dkr.ecr.us-east-1.amazonaws.com # happy-ecr
      # prefix: 608713827966.dkr.ecr.us-east-1.amazonaws.com # happy-ecr
      api_url: https://636078031259.dkr.ecr.us-east-1.amazonaws.com # babers-ecr
      prefix: 636078031259.dkr.ecr.us-east-1.amazonaws.com # babers-ecr
      credentials: pullsecret:argocd/ecr-credentials  # Created by CronJob
      default: true

logLevel: info
interval: 2m

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

image:
  repository: quay.io/argoprojlabs/argocd-image-updater
  pullPolicy: IfNotPresent
  tag: "v0.14.0"

extraArgs:
  - --health-port=8080
  - --metrics-port=8081

extraEnv:
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_DEFAULT_REGION
    value: us-east-1