controller:
  replicaCount: 2

  serviceAccount:
    create: true
    name: ingress-nginx

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-089f6c8ea4288c660, subnet-04d2152d00d34a7af, subnet-05cd11b4c821581a0"

  # Disable non-essential features
  metrics:
    enabled: false
  admissionWebhooks:
    enabled: false

  ingressClassResource:
    name: nginx
    enabled: true
    default: true

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    proxy-body-size: "10m"
    ssl-protocols: "TLSv1.2 TLSv1.3"