apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/BIGRS-ITI/Platform.git
    targetRevision: prod
    path: helm-values
    directory:
      include: cluster_issuer.yaml
  
  destination:
    server: https://kubernetes.default.svc
    # ClusterIssuer is cluster-scoped, but we specify cert-manager namespace
    namespace: cert-manager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # cert-manager namespace already exists
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
