apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # Deploy AFTER external-secrets (wave 4)
spec:
  project: default

  # Reference the SecretStore from git
  source:
    repoURL: https://github.com/BIGRS-ITI/Platform
    path: argo-apps
    targetRevision: HEAD

  # Where to install in the cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  # ArgoCD automation settings
  syncPolicy:
    automated:
      prune: true       # Remove old resources not in Git
      selfHeal: true    # Auto-fix drift
    syncOptions:
      - CreateNamespace=true
