apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy after cert-manager & ingress
spec:
  project: default

  # Where to get the chart
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.0.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/helm-values/external-secrets-values.yaml
      
    - repoURL: https://github.com/BIGRS-ITI/Platform.git
      targetRevision: main
      ref: values

  # Where to install in the cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  # ArgoCD automation settings
  syncPolicy:
    automated:
      prune: true       # Remove old resources not in Git
      selfHeal: true    # Auto-fix drift
    syncOptions:
      - CreateNamespace=true  # Auto-create target namespace if missing
