apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-frontend
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations for automatic image updates
    argocd-image-updater.argoproj.io/image-list: frontend=608713827966.dkr.ecr.us-east-1.amazonaws.com/taskmanager-app
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^frontend-[0-9]+$
    argocd-image-updater.argoproj.io/frontend.image-name: frontend-latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/BIGRS-ITI/Platform.git
    targetRevision: main
    path: apps/Frontend
  
  destination:
    server: https://kubernetes.default.svc
    namespace: taskmanager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
