apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd-image-updater.argoproj.io/image-list:
      # babers ECR images
      backend=636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-backend, 
      frontend=636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-frontend
      # happy ECR images
      # backend=608713827966.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-backend,
      # frontend=608713827966.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-frontend 

    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build

    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^backend-([0-9]+)$
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^frontend-([0-9]+)$
    
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.force-update: "true"

    argocd-image-updater.argoproj.io/backend.ignore-tags: backend-latest
    argocd-image-updater.argoproj.io/frontend.ignore-tags: frontend-latest

    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/backend.image-name: 636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-backend
    argocd-image-updater.argoproj.io/frontend.image-name: 636078031259.dkr.ecr.us-east-1.amazonaws.com/bigrs-nodejs-app-frontend
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update image {{.Image}} to {{.NewTag}}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/BIGRS-ITI/Platform.git
    targetRevision: main
    path: apps/nodejs-app
  
  destination:
    server: https://kubernetes.default.svc
    namespace: taskmanager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

